import {
  Center,
  Heading,
  Flex,
  Text,
  VStack,
  Box,
  useMediaQuery,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Editor } from "components/editor";
import Hints from "components/hints";
import { useState } from "react";
import { Navbar } from "components/navbar";

import { DrillWithHintsAndTestCases } from "types/drill";
import { DrillCompletion } from "@prisma/client";

const Home: NextPage = () => {
  const [visibleHints, setVisibleHints] = useState(0);
  const [isLargerThan600] = useMediaQuery("(min-width: 600px)");

  return (
    <div>
      <Head>
        <title>Drills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Flex mt={8} alignItems="center" justifyContent="center">
          <Center>
            <VStack>
              <Heading color="primary-text">⚡️Drills⚡️</Heading>
              <Text color="secondary-text">
                Best way to master JS fundamentals. Try it now 👇🏼
              </Text>

              <Box
                p={4}
                sx={{
                  ".sp-wrapper": {
                    width: isLargerThan600 ? "560px" : "340px",
                  },
                }}
              >
                <Hints
                  setVisibleHints={setVisibleHints}
                  visibleHints={visibleHints}
                  drill={drill}
                />
                <Editor
                  drill={drill}
                  visibleHints={visibleHints}
                  setVisibleHints={setVisibleHints}
                />
              </Box>
            </VStack>
          </Center>
        </Flex>
      </main>
    </div>
  );
};

// const drill = {
//   functionName: "doubleNumber",
//   language: "js",
//   starterCode: `
//   const doubleNumber = (number) => {
//     // your code goes here. Good luck 🍀
//   };

//   export default doubleNumber;`,
//   testCases: [
//     { input: 1, output: 2 },
//     { input: 4, output: 8 },
//   ],
//   hints: [
//     "To write this function you need to use the `*` operator of JavaScript",
//     "The return statement should look like `return number * 2;`",
//   ],
// };
const drill: DrillWithHintsAndTestCases & { completion: DrillCompletion } = {
  id: 1,
  completion: null,
  functionName: "doubleNumber",
  language: "js",
  starterCode: `
  const doubleNumber = (number) => {
    // your code goes here. Good luck 🍀
  };

  export default doubleNumber;`,
  testCases: [
    { id: "a", drillId: 1, input: 1, output: 2 },
    { id: "b", drillId: 1, input: 4, output: 8 },
  ],
  hints: [
    {
      id: "a",
      drillId: 1,
      text: "To write this function you need to use the `*` operator of JavaScript",
    },
    {
      id: "b",
      drillId: 1,
      text: "The return statement should look like `return number * 2;`",
    },
  ],
  difficulty: "HARD",
  explainerVideo: null,
  description:
    "You are asked to write a `function` that accepts a number and returns the _doubled number_.",
};

export default Home;
