import { Center, Heading, Flex, Text, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Drills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex h="100vh" w="100%" alignItems="center" justifyContent="center">
          <Center>
            <VStack>
              <Heading color="primary-text">Drills</Heading>
              <Text color="secondary-text">
                Best way to master JS fundamentals
              </Text>
            </VStack>
          </Center>
        </Flex>
      </main>
    </div>
  );
};

export default Home;
